/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef CGADMOB_AUTODEFS_H
#define CGADMOB_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_CGADMOB_NAME "CGAdMob"
#define S3E_EXT_CGADMOB_HASH 0xbfdc71f2

#ifdef S3E_EXT_REGISTER
#ifndef S3E_EXT_REGISTER_KEY
#define S3E_EXT_REGISTER_KEY(name, num, key) S3E_EXT_REGISTER(name, num)
#endif
S3E_EXT_REGISTER("CGAdMob", 13)
#else

#endif /* S3E_EXT_REGISTER */
#endif /* !CGADMOB_AUTODEFS_H */
