/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
/*
 * This file contains the automatically generated loader-side
 * functions that form part of the extension.
 *
 * This file is awlays compiled into all loaders but compiles
 * to nothing if this extension is not enabled in the loader
 * at build time.
 */
#include "IwDebug.h"
#include "CGAdMob_autodefs.h"
#include "s3eEdk.h"
#include "CGAdMob.h"
//Declarations of Init and Term functions
extern s3eResult CGAdMobInit();
extern void CGAdMobTerminate();


// On platforms that use a seperate UI/OS thread we can autowrap functions
// here.   Note that we can't use the S3E_USE_OS_THREAD define since this
// code is oftern build standalone, outside the main loader build.
#if defined I3D_OS_IPHONE || defined I3D_OS_OSX || defined I3D_OS_LINUX || defined I3D_OS_WINDOWS

static void InitAdView_wrap()
{
    IwTrace(CGADMOB_VERBOSE, ("calling CGAdMob func on main thread: InitAdView"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)InitAdView, 0);
}

static bool ShowInterstitialAd_wrap()
{
    IwTrace(CGADMOB_VERBOSE, ("calling CGAdMob func on main thread: ShowInterstitialAd"));
    return (bool)(intptr_t)s3eEdkThreadRunOnOS((s3eEdkThreadFunc)ShowInterstitialAd, 0);
}

static void SetGoogleAppKey_wrap(const char* bannerAdUnitId, const char* interstatialAdUnitId)
{
    IwTrace(CGADMOB_VERBOSE, ("calling CGAdMob func on main thread: SetGoogleAppKey"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)SetGoogleAppKey, 2, bannerAdUnitId, interstatialAdUnitId);
}

static void BannerAdLoad_wrap()
{
    IwTrace(CGADMOB_VERBOSE, ("calling CGAdMob func on main thread: BannerAdLoad"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)BannerAdLoad, 0);
}

static void BannerAdShow_wrap()
{
    IwTrace(CGADMOB_VERBOSE, ("calling CGAdMob func on main thread: BannerAdShow"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)BannerAdShow, 0);
}

static void BannerAdHide_wrap()
{
    IwTrace(CGADMOB_VERBOSE, ("calling CGAdMob func on main thread: BannerAdHide"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)BannerAdHide, 0);
}

static void Release_wrap()
{
    IwTrace(CGADMOB_VERBOSE, ("calling CGAdMob func on main thread: Release"));
    s3eEdkThreadRunOnOS((s3eEdkThreadFunc)Release, 0);
}

#define InitAdView InitAdView_wrap
#define ShowInterstitialAd ShowInterstitialAd_wrap
#define SetGoogleAppKey SetGoogleAppKey_wrap
#define BannerAdLoad BannerAdLoad_wrap
#define BannerAdShow BannerAdShow_wrap
#define BannerAdHide BannerAdHide_wrap
#define Release Release_wrap

#endif

void CGAdMobRegisterExt()
{
    /* fill in the function pointer struct for this extension */
    void* funcPtrs[7];
    funcPtrs[0] = (void*)InitAdView;
    funcPtrs[1] = (void*)ShowInterstitialAd;
    funcPtrs[2] = (void*)SetGoogleAppKey;
    funcPtrs[3] = (void*)BannerAdLoad;
    funcPtrs[4] = (void*)BannerAdShow;
    funcPtrs[5] = (void*)BannerAdHide;
    funcPtrs[6] = (void*)Release;

    /*
     * Flags that specify the extension's use of locking and stackswitching
     */
    int flags[7] = { 0 };

    /*
     * Register the extension
     */
s3eEdkRegister("CGAdMob", funcPtrs, sizeof(funcPtrs), flags, CGAdMobInit, CGAdMobTerminate, 0);
}

#if !defined S3E_BUILD_S3ELOADER

#if defined S3E_EDK_USE_STATIC_INIT_ARRAY
int CGAdMobStaticInit()
{
    void** p = g_StaticInitArray;
    void* end = p + g_StaticArrayLen;
    while (*p) p++;
    if (p < end)
        *p = (void*)&CGAdMobRegisterExt;
    return 0;
}

int g_CGAdMobVal = CGAdMobStaticInit();

#elif defined S3E_EDK_USE_DLLS
S3E_EXTERN_C S3E_DLL_EXPORT void RegisterExt()
{
    CGAdMobRegisterExt();
}
#endif

#endif
