# -*- coding: utf-8 -*-
# Deployment settings for CGAdmobExample.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['/Applications/Marmalade.app/Contents/s3e/makefile_builder/mkb.py', '/Users/adriangomez/OneDrive/Development/CGAdmobExample/CGAdmobExample.mkb', '--deploy-only', '--hub-data', '/Users/adriangomez/OneDrive/Development/CGAdmobExample/project_CGAdmobExample/mkb-scons.txt', '--buildenv=SCONS']
mkb = '/Users/adriangomez/OneDrive/Development/CGAdmobExample/CGAdmobExample.mkb'
mkf = ['/Applications/Marmalade.app/Contents/s3e/s3e-default.mkf', '/Applications/Marmalade.app/Contents/modules/iwutil/iwutil.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libjpeg/libjpeg.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/libpng/libpng.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/zlib/zlib.mkf', '/Applications/Marmalade.app/Contents/modules/iwgl/iwgl.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/cocos2dx/cocos2dx/proj.marmalade/cocos2dx.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/cocos2dx/cocos2dx/platform/third_party/marmalade/libxml2.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/cocos2dx/cocos2dx/platform/third_party/marmalade/freetype.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/cocos2dx/cocos2dx/platform/third_party/marmalade/libtiff/libtiff.mkf', '/Applications/Marmalade.app/Contents/modules/third_party/cocos2dx/external/Box2D/proj.marmalade/Box2D.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('/Users/adriangomez/OneDrive/Development/CGAdmobExample/data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'CGAdmobExample'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'CGAdmobExample'
    long_caption = 'CGAdmobExample'
    version = [0, 0, 1]
    config = ['/Users/adriangomez/OneDrive/Development/CGAdmobExample/data/app.icf']
    data_dir = '/Users/adriangomez/OneDrive/Development/CGAdmobExample/data'
    iphone_link_lib = []
    osx_ext_dll = []
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = []
    wp8_ext_capabilities = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    ws8_extra_res = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_x86/debug/CGAdmobExample.so',
                   'release' : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_x86/release/CGAdmobExample.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_x86/debug/CGAdmobExample.s86',
                   'release' : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_x86/release/CGAdmobExample.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_firefoxos/debug/CGAdmobExample.js',
                   'release' : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_firefoxos/release/CGAdmobExample.js',
                 },
         'arm_gcc' : {
                   'debug'   : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_arm/debug/CGAdmobExample.s3e',
                   'release' : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_arm/release/CGAdmobExample.s3e',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_x86/debug/CGAdmobExample.so',
                   'release' : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_x86/release/CGAdmobExample.so',
                 },
         'x86' : {
                   'debug'   : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_x86/debug/CGAdmobExample.s86',
                   'release' : r'/Users/adriangomez/OneDrive/Development/CGAdmobExample/build_cgadmobexample_scons_x86/release/CGAdmobExample.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
